---
title: Heirloom recipies
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tom.c.kuhn@gmail.com
description: A website dedicated to heirloom recipies for the next generation
baseurl: ''
url: ''
twitter_username: tom_kuhn
github_username: tom-kuhn
markdown: kramdown
remote_theme: broccolini/swiss
theme: jekyll-swiss
plugins:
- jekyll-feed
