---
title: Heirloom recipies
timezone: UTC
collections:
  mains:
    title: mains
    output: true
    banner-url: "/assets/images/brooke-lark-500141-unsplash-1.jpg"
    order: 1
  cakes:
    title: cakes
    output: true
    banner-url: "/assets/images/jill-heyer-189419-unsplash-1.jpg"
    order: 2
email: tom.c.kuhn@gmail.com
description: A website dedicated to heirloom recipies for the next generation
baseurl: ''
url: ''
twitter_username: tom_kuhn
github_username: tom-kuhn
markdown: kramdown
remote_theme: broccolini/swiss
theme: jekyll-swiss
plugins:
- jekyll-feed
